### ISSUE TITLE
Killing Floor

### ISSUE THREAD

**Issue by OJMoody** [Ballistic-Weapons-Community/BallisticWeapons#19]
Make the mod work for killing floor. Current tasks to do:

-Assets need a rejig to make sure all assets the ballisticprov55 requires is in the bwcore packages
-The reload and ADS need to sync up with the kf games version of the buttons (Code exists, just needs transfering from 2.5)
-New mutators are required to get the weapons in the shop (Code exists, just needs transfering from 2.5)
-Params need to be synced up with the games version of ammo
-Ut2k4 Effects, statics & sounds to be later referred to in their KF version
-Similar work will be needed for all the bonus pack weapons (Will be WIP once bugs are ironed out)
-Understand why projectiles dont work
-Understand why some guns outright dont work

**Comment by MarcMoylan** [comment]
canceled
