### ISSUE TITLE
Airstrikes Firemodes

### ISSUE THREAD

**Issue by OJMoody** [Ballistic-Weapons-Community/BallisticWeapons#4]
Some work, Some dont:

AIMS-9 Severely Underpowered (Damage & Range)
Carpet Bombing Works
CBU-30 Chemical Cluster Bomb Doesn't Summon
CBU-58 Incendiary Cluster Bomb No Damage
CBU-72 Cluster Bomb Underpowered (Range)
CBU-100 Cluster Bomb Works
GPU-57 MOP Works
AGM-154 JSOW Works
MC1 Chemical Bomb No Damage (Toxic Sound needs Renewal)
MK77 Incendiary Bomb No Fire Damage (Initial Explo Damage Works)
MRLS Rocket Barrage Works
Napalm Carpet Bombing Doesn't Summon

**Comment by NOOTLORD** [comment]
Closing since all mentioned modes work correctly now
