### ISSUE TITLE
Mouse settings not saving when BW is active

### ISSUE THREAD

**Issue by NOOTLORD** [Ballistic-Weapons-Community/BallisticWeapons#57]
**Bug description:** 
When BW is active and u try to change your mouse settings trough the settings menu u will notice if u change the number and u exit and re-enter the settings menu the value has returned to default. The value u entered has saved but will be reset once u exit the game.
I seen this issue with FoxFOV aswell in the past and it seemed the way he fixed it was by providing his own settings tab that has the new playerinput class linked. See this commit for a example: https://github.com/alexstrout/foxWSFix-UT2k4/commit/a3ffefd338ec980ef3372fe1d752da201896ed96#diff-bf5948222257b28059f529283a256e5152cbd1e3d73ab8a3a5d8e1e486848728

**Branch:**
Dev

**Build from commit:** 
9208734

**How to replicate:**
Change your mouse sensitivity in the input settings tab and exit the settings page, re-enter the input settings tab again and u will see that your set value is gone and replaced by the default value (which is the value set in the ini)

**Comment by Azarael** [comment]
Should remove BallisticPlayerInput class.

**Comment by NOOTLORD** [comment]
Issue seems fixed now, will remove the BallisticPlayerInput class as its not being used anymore
