### ISSUE TITLE
X83 Irons Defaults to Scope in Turret Mode

### ISSUE THREAD

**Issue by StormX49** [Ballistic-Weapons-Community/BallisticWeapons#84]
**Bug description:**
When using the Iron Sight layout on the X83, going in and out of turret mode defaults to the original scope layout. 

**Commit used:**
e3dd2d6

**Online or Offline?**
Both.

**Steps to replicate:**
Select Irons for the X83 and then go into turret mode, then exit turret mode.

**Comment by MarcMoylan** [comment]
reverting for now
