### ISSUE TITLE
5.56 Spectre Missing firing Sounds in Classic.

### ISSUE THREAD

**Issue by StormX49** [Ballistic-Weapons-Community/BallisticWeapons#85]
**Bug description:**
When using the 5.56 layout for the Specter AR in classic, there's no firing sound for it.

**Commit used:**
e3dd2d6

**Online or Offline?**
Both

**Steps to replicate:**
Select the 5.56 layout for the Specter and fire away.

**Comment by MarcMoylan** [comment]
fixed
